### ISSUE TITLE
User should be able to see a list of actions after they join the campaign

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#29]
Use the following [screenshot](https://user-images.githubusercontent.com/1425162/67032005-0316a880-f113-11e9-80fa-35742d42e4ca.png) as a base to develop a UI that allows a user to see the actions for a current campaign.

The expected modifications within the UI are that the "GO" button is not going to be there but instead the user click the action row and a descriptions will be expanded _(markdown rich)_ with a **link that on click will mark the action as completed**.

In further iterations we can work with Twitter or Facebook API to support more complex actions

**Acceptance Criteria**
- [x] Make sure to have a service to work with
- [x] Create a basic UI to display actions
- [x] Integrate actions UI with campaign service
- [x] Fix deployment issue with Apollo
- [x] Have a PR with the actions listing in a isolated page

**Comment by duranmla** [comment]
I have completed the base of the service by adding an extra mutation that allow the user to set the UserAction completed value to true/false. In that sense, we now have a service to work with. Take a look at the temporary repository for that service at https://github.com/duranmla/social-giveaways

The latest commit with mutation can be found at https://github.com/duranmla/social-giveaways/commit/036fb41a52d8274d2b630cbbf3195e9eed6c212a

**Comment by duranmla** [comment]
I have done some updates into the https://github.com/duranmla/social-giveaways project related to allow the resolvers to actually be exposed within the API 🚎 

Besides, I have added the support to use Apollo within the Gatsby site _(this project)_ and currently I am working towards finish a basic UI and verification flow

**Comment by duranmla** [comment]
Latest code related to the actions campaigns are here https://github.com/debtcollective/student-debt-campaign-netlify/tree/ad/campaignActions

**Comment by duranmla** [comment]
After today's meeting with @orlando we did some changes:

- We are going to remove the verification column from the service
- Add a type and JSONB column into the action model on the service _(Type for action UI, JSONB for params in order to consume the action UI. ex. type Link, config href="foo")_
- The **UI** is on the website is going to follow the FAQ section pattern
- We need a strikeout style for completed actions

_(first action we want to support is redirect user to a link and complete action after delay)_

**Comment by duranmla** [comment]
I have updated the service models https://github.com/duranmla/social-giveaways/commit/7ff26d2c29e3fea6ad43d20608bd8b75f89defd9

**Comment by duranmla** [comment]
Currently, the open PR has an issue related to the build process. I have to take a look and also move the actions into an isolated page _(which is going to be a private route for logged users)_. In order to close this issue:

- [ ] Fix deployment issue
- [ ] Have a PR with the actions listing in a isolated page

**Comment by duranmla** [comment]
I have updated the PR to successfully built and have the campaign section with actions within their own isolated page of `actions` https://github.com/debtcollective/student-debt-campaign-netlify/pull/15

**Comment by duranmla** [comment]
This issue is related to the Epic https://github.com/debtcollective/student-debt-campaign/issues/31 nevertheless in order to complete the epic we need Session epic first https://github.com/debtcollective/student-debt-campaign/issues/3
