### ISSUE TITLE
Research Actions

### ISSUE THREAD

**Issue by orlando** [debtcollective/student-debt-campaign#4]
**What:** Research Actions

**Why:** **Actions** is our way to enable users to spread the word of our campaign. Actions will look like this:

- Follow The Debt Collective on Twitter
- Follow Strike Student Debt on Facebook
- Retweet a specific Tweet

The list of actions is TBD, but every action needs to have:

1. Something actionable the user needs to do.
2. A way for us to verify the user did what it was meant to do.
3. Reward the user.

**How:** The research show include:

- Define how we will implement actions (messages and interfaces)
- Define how we will store data for actions. Consider that If the deployment is done outside AWS, we won't be able to access RDS (Postgres) databases from outside
- Define how we will be doing the deployment of this app.
- Define how we will consume SSO from Discourse. The fundraising app has this implemented already.

The app doesn't need to be tighed to Netlify, we can use Netlify to host the CMS app of the campaign website, and deploy a small GraphQL API in AWS to do data persistence.

**Comment by orlando** [comment]
Closing this, we started with the implementation

**Comment by duranmla** [comment]
Just to follow up the update here.
The document specification can be found [here](https://www.notion.so/duranmla/4-Campaign-Actions-8984cc7de0984c349847c7c7c8d5ab53).
Whereas what we have already built up until now can be found [here](https://github.com/duranmla/social-giveaways)

Basically, we have a service that expose a GraphQL API that allow us to work with Campaigns, Actions and Users. That service needs later to be integrated with the campaign website in order to work as intended.
